### ISSUE TITLE
Skript commands throw an exception when run in command blocks

### ISSUE THREAD

**Issue by RoyCurtis** [Gamealition/Survival-Skripts#7]
# Exception

```
[12:05:31 WARN]: CommandBlock at (-4119,146,-1999) failed to handle command
java.lang.NullPointerException
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[patched_1.9.2.jar:git-Paper-706]
        at net.minecraft.server.v1_9_R1.CommandBlockListenerAbstract.executeCommand(CommandBlockListenerAbstract.java:218) [patched_1.9.2.jar:git-Paper-706]
        at net.minecraft.server.v1_9_R1.CommandBlockListenerAbstract.a(CommandBlockListenerAbstract.java:103) [patched_1.9.2.jar:git-Paper-706]
        at net.minecraft.server.v1_9_R1.BlockCommand.b(BlockCommand.java:77) [patched_1.9.2.jar:git-Paper-706]
        at net.minecraft.server.v1_9_R1.WorldServer.a(WorldServer.java:747) [patched_1.9.2.jar:git-Paper-706]
        at net.minecraft.server.v1_9_R1.WorldServer.doTick(WorldServer.java:249) [patched_1.9.2.jar:git-Paper-706]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:867) [patched_1.9.2.jar:git-Paper-706]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.9.2.jar:git-Paper-706]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:721) [patched_1.9.2.jar:git-Paper-706]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:620) [patched_1.9.2.jar:git-Paper-706]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```
# Example code

```
command /ni-wrong <text> <player>:
    permission: gamealition.admin
    executable by: console
    trigger:
        # Logic
        set {_dest} to arg 1
        set {_player} to arg 2
        execute console command "/mvtp %{_player}% %{_dest}%"
        message "&c*** Wrong answer! Please try again" to {_player}

        {_player} has permission "gamealition.group.default"
        add 1 to {approval.wrong.%{_player}%}

        if {approval.wrong.%{_player}%} >= {@max wrong answers}:
            delete {approval.wrong.%{_player}%}
            execute console command "/ban %{_player}% {@wrong answer message}"
        else:
            message "*** Wrong newbie island answer by %{_player}%, total %{approval.wrong.%{_player}%}%" to console
```

**Comment by RoyCurtis** [comment]
Potentially a PaperSpigot issue - https://github.com/PaperMC/Paper/issues/256

**Comment by RoyCurtis** [comment]
Was a Skript issue; resolved thanks to a workaround in PaperSpigot. Fix pending for Skript
